packages:
  - apps/*
  - packages/*
  - scripts
  - tooling/*
  - jargal

catalog:
  '@better-auth/cli': 1.4.0-beta.9
  '@better-auth/expo': 1.4.0-beta.9
  '@codeandmoney/agvan': 0.0.0-dev.3
  '@codeandmoney/soelma': 0.0.0-dev.2
  '@eslint/js': 9.39.2
  '@storybook/addon-a11y': 10.1.1
  '@storybook/addon-docs': 10.1.1
  '@storybook/addon-ondevice-actions': 10.1.1
  '@storybook/addon-ondevice-controls': 10.1.1
  '@storybook/addon-vitest': 10.1.1
  '@storybook/react-native': 10.1.1
  '@storybook/react-vite': 10.1.1
  '@stylexjs/babel-plugin': 0.17.4
  '@stylexjs/eslint-plugin': 0.17.4
  '@stylexjs/postcss-plugin': 0.17.4
  '@stylexjs/stylex': 0.17.4
  '@stylexjs/unplugin': 0.17.4
  '@tanstack/react-form': 1.27.4
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-router': 1.143.3
  '@tanstack/react-router-devtools': 1.143.3
  '@tanstack/react-router-ssr-query': 1.143.3
  '@tanstack/react-start': 1.143.3
  '@types/bun': 1.3.5
  '@types/luxon': 3.7.1
  '@types/node': 22.13.14
  '@vitejs/plugin-react': 5.1.2
  better-auth: 1.4.7
  es-toolkit: 1.43.0
  eslint: 9.39.2
  eslint-plugin-storybook: 10.1.1
  ky: 1.11.0
  metro-cache: ^0.83.3
  neverthrow: ^8.2.0
  prettier: 3.7.4
  storybook: 10.1.1
  tiny-invariant: 1.3.3
  typescript: 5.9.3
  valibot: 1.1.0
  vite: 7.3.0
  vite-tsconfig-paths: 6.0.3

catalogs:
  expo:
    '@expo-google-fonts/cormorant-garamond': 0.4.1
    '@expo/vector-icons': ^15.0.3
    expo: 54.0.30
    expo-application: 7.0.8
    expo-constants: 18.0.10
    expo-dev-client: 6.0.16
    expo-font: 14.0.10
    expo-haptics: ^15.0.8
    expo-image: ^3.0.11
    expo-linking: 8.0.11
    expo-router: 6.0.21
    expo-secure-store: 15.0.7
    expo-splash-screen: 31.0.13
    expo-status-bar: 3.0.9
    expo-symbols: 1.0.8
    expo-system-ui: 6.0.9
    expo-web-browser: 15.0.10
  react-19:
    '@types/react': 19.1.0
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
  react-native:
    '@react-native-async-storage/async-storage': ^2.2.0
    '@react-native-community/datetimepicker': ^8.5.1
    '@react-native-community/slider': ^5.1.1
    react-native: 0.81.5
    react-native-gesture-handler: 2.28.0
    react-native-mmkv-storage: ^12.0.1
    react-native-reanimated: 4.1.3
    react-native-safe-area-context: 5.6.2
    react-native-screens: 4.16.0
    react-native-svg: 15.15.1
    react-native-worklets: 0.5.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
